/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_tiros_api_Http */

#ifndef _Included_cn_com_tiros_api_Http
#define _Included_cn_com_tiros_api_Http
#ifdef __cplusplus
extern "C" {
#endif
//#undef cn_com_tiros_api_Http_NSEERR_DICONNECT
//#define cn_com_tiros_api_Http_NSEERR_DICONNECT 600L
//#undef cn_com_tiros_api_Http_NSEERR_CLIENTERR
//#define cn_com_tiros_api_Http_NSEERR_CLIENTERR 601L
//#undef cn_com_tiros_api_Http_NSEERR_TIMEOUT_RESPONSE
//#define cn_com_tiros_api_Http_NSEERR_TIMEOUT_RESPONSE 700L
//#undef cn_com_tiros_api_Http_NSEERR_TIMEOUT_DATA
//#define cn_com_tiros_api_Http_NSEERR_TIMEOUT_DATA 701L
//#undef cn_com_tiros_api_Http_NSEERR_TOTALLENERR
//#define cn_com_tiros_api_Http_NSEERR_TOTALLENERR 702L
//#undef cn_com_tiros_api_Http_NETSTATE_RUNNING
//#define cn_com_tiros_api_Http_NETSTATE_RUNNING 0L
//#undef cn_com_tiros_api_Http_NETSTATE_WAIT
//#define cn_com_tiros_api_Http_NETSTATE_WAIT 1L
/*
 * Class:     cn_com_tiros_api_Http
 * Method:    sys_httpEvent
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_cn_com_tiros_api_Http_sys_1httpEvent__IIII
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     cn_com_tiros_api_Http
 * Method:    sys_httpEvent
 * Signature: (III[B)V
 */
JNIEXPORT void JNICALL Java_cn_com_tiros_api_Http_sys_1httpEvent__III_3B
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray);

/*
 * Class:     cn_com_tiros_api_Http
 * Method:    sys_httpEvent
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_com_tiros_api_Http_sys_1httpEvent__IIILjava_lang_String_2
  (JNIEnv *, jclass, jint, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
