/*
 * @file cn_com_tiros_api_Http.h
 * @Author: wangxt<wangxt@tiros.com.cn>
 * @Created on: 2014-6-19
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_tiros_api_Http */

#ifndef _Included_cn_com_tiros_api_Http
#define _Included_cn_com_tiros_api_Http
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     cn_com_tiros_api_Http
 * Method:    sys_httpEvent
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_cn_com_tiros_api_Http_sys_1httpEvent__IIII
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     cn_com_tiros_api_Http
 * Method:    sys_httpEvent
 * Signature: (III[B)V
 */
JNIEXPORT void JNICALL Java_cn_com_tiros_api_Http_sys_1httpEvent__III_3B
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray);

/*
 * Class:     cn_com_tiros_api_Http
 * Method:    sys_httpEvent
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_com_tiros_api_Http_sys_1httpEvent__IIILjava_lang_String_2
  (JNIEnv *, jclass, jint, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
