/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_tiros_api_Timerr */

#ifndef _Included_cn_com_tiros_api_Timerr
#define _Included_cn_com_tiros_api_Timerr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_tiros_api_Timerr
 * Method:    sys_timerEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_com_tiros_api_Timerr_sys_1timerEvent
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
