//测试代码，不用审核

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xc_api_testclass */

#ifndef _Included_xc_api_testclass
#define _Included_xc_api_testclass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xc_api_testclass
 * Method:    printnativelog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xc_api_testclass_printnativelog
  (JNIEnv *, jclass);

/*
 * Class:     xc_api_testclass
 * Method:    filetest
 * Signature: ()I
 */

JNIEXPORT jint JNICALL Java_xc_api_testclass_filetest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
