/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_tiros_api_MThread */

#ifndef _Included_cn_com_tiros_api_MThread
#define _Included_cn_com_tiros_api_MThread
#ifdef __cplusplus
extern "C" {
#endif
#undef cn_com_tiros_api_MThread_MIN_PRIORITY
#define cn_com_tiros_api_MThread_MIN_PRIORITY 1L
#undef cn_com_tiros_api_MThread_NORM_PRIORITY
#define cn_com_tiros_api_MThread_NORM_PRIORITY 5L
#undef cn_com_tiros_api_MThread_MAX_PRIORITY
#define cn_com_tiros_api_MThread_MAX_PRIORITY 10L
/*
 * Class:     cn_com_tiros_api_MThread
 * Method:    SYS_ThreadProcFunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_com_tiros_api_MThread_SYS_1ThreadProcFunc
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_com_tiros_api_MThread
 * Method:    SYS_ThreadNotifyFunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_com_tiros_api_MThread_SYS_1ThreadNotifyFunc
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
