/*
 * @file cn_com_tiros_api_MThread.h
 * @Author: wangxt<wangxt@tiros.com.cn>
 * @Created on: 2014-6-19
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_tiros_api_MThread */

#ifndef _Included_cn_com_tiros_api_MThread
#define _Included_cn_com_tiros_api_MThread
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     cn_com_tiros_api_MThread
 * Method:    SYS_ThreadProcFunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_com_tiros_api_MThread_SYS_1ThreadProcFunc
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_com_tiros_api_MThread
 * Method:    SYS_ThreadNotifyFunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_com_tiros_api_MThread_SYS_1ThreadNotifyFunc
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
